kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: cicd/dockerfile
    app.openshift.io/vcs-uri: "https://git.cardiff.ac.uk/c21063494/assessmenttracking"
  name: assessmenttracking-cicd-dockerfile-generated-${CI_COMMIT_SHORT_SHA}
  managedFields:
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: "2024-02-09T16:15:57Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:status":
          "f:lastVersion": {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: "2024-02-13T12:45:13Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:app.openshift.io/vcs-ref": {}
            "f:app.openshift.io/vcs-uri": {}
            "f:openshift.io/generated-by": {}
          "f:labels":
            .: {}
            "f:app": {}
            "f:app.kubernetes.io/component": {}
            "f:app.kubernetes.io/instance": {}
            "f:app.kubernetes.io/name": {}
            "f:app.kubernetes.io/part-of": {}
        "f:spec":
          "f:output":
            "f:pushSecret":
              .: {}
              "f:name": {}
            "f:to":
              .: {}
              "f:kind": {}
              "f:name": {}
          "f:runPolicy": {}
          "f:source":
            "f:contextDir": {}
            "f:git":
              .: {}
              "f:ref": {}
              "f:uri": {}
            "f:sourceSecret":
              .: {}
              "f:name": {}
            "f:type": {}
          "f:strategy":
            "f:dockerStrategy":
              .: {}
              "f:dockerfilePath": {}
            "f:type": {}
          "f:triggers": {}
  namespace: assessment-tracker
  labels:
    app: assessmenttracking-cicd-dockerfile
    app.kubernetes.io/component: assessmenttracking-cicd-dockerfile
    app.kubernetes.io/instance: assessmenttracking-cicd-dockerfile
    app.kubernetes.io/name: assessmenttracking-cicd-dockerfile
    app.kubernetes.io/part-of: assessmenttracking-app
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: >-
        registry.git.cf.ac.uk/c21063494/assessmenttracking/cicd-dockerfile:${CI_COMMIT_SHORT_SHA}
    pushSecret:
      name: registry-git-cf-ac-uk
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://git.cardiff.ac.uk/c21063494/assessmenttracking"
      ref: cicd/dockerfile
    contextDir: /
    sourceSecret:
      name: git
  triggers:
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 59
